services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_pgvector_chatbot
    restart: unless-stopped

    ports:
      - '5432:5432'

    environment:
      POSTGRES_DB: app_chatbot_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

    volumes:
      - ./db_data_docker:/var/lib/postgresql/data
